=== quantmth1908038/java/XML/Lab_02/FPTAptech.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://xmlpowercorp"
            xmlns="http://xmlpowercorp"
            elementFormDefault="qualified">
    <xsd:element name="FPTAptech" type="FPTAptechType"/>

    <xsd:complexType name="FPTAptechType">
        <xsd:sequence>
            <xsd:element name="Student" type="StudentType" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="StudentType">
        <xsd:sequence>
            <xsd:element name="Name" type="NameType"/>
            <xsd:element name="Age">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minInclusive value="14"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="Sex">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="Male"/>
                    <xsd:pattern value="Female"/>
                    <xsd:pattern value="t"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>
    <xsd:complexType name="NameType">
        <xsd:sequence>
            <xsd:element name="FName" type="xsd:string"/>
            <xsd:element name="LName" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>

</xsd:schema>

=== quantmth1908038/java/XML/Lab_02/FPTAptech.xml
<?xml version="1.0" encoding="UTF-8"?>

<FPTAptech xmlns="http://xmlpowercorp"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://xmlpowercorp FPTAptech.xsd">
    <Student Sex="Female">
        <Name>
            <FName>Dinh</FName>
            <LName>Anh</LName>
        </Name>
        <Age>18</Age>
    </Student>
    <Student Sex="Female">
        <Name>
            <FName>Phan</FName>
            <LName>Tu</LName>
        </Name>
        <Age>22</Age>
    </Student>
    <Student Sex="Male">
        <Name>
            <FName>Kiet</FName>
            <LName>Do</LName>
        </Name>
        <Age>15</Age>
    </Student>
</FPTAptech>
